name: HH Daily Update

on:
  schedule:
    - cron: '6 21 * * *'  # 00:01 МСК = 21:01 UTC
  workflow_dispatch:     # Позволяет запускать вручную

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python fetch_hh_daily.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
